---
- hosts: all
  become_user: root
  become_method: sudo

  roles:
    - system-update
    - puppet-install
    - shellcheck-install
    - java-install
    - python-install

  tasks:
    - include_vars: "{{item}}"
      with_first_found:
        - 'pkg-names-{{ansible_distribution}}.yaml'
        - 'pkg-names-{{ansible_os_family}}.yaml'
        - 'pkg-names.yaml'

    - name: Setup SELINUX
      setlinux:
        policy: targeted
        state: enforcing
      when: ansible_os_family == 'RedHat'
      become: yes

    - name: Allow jenkins user ability to switch Java versions
      copy:
        dest: /etc/sudoers.d/89-jenkins-user-defaults
        content: |
          Defaults:jenkins !requiretty
          jenkins ALL = NOPASSWD: ALL
        validate: /usr/sbin/visudo -cf %s
      become: yes

    - name: Install base packages
      include_tasks: '{{item}}'
      with_first_found:
        - 'install-base-pkgs-{{ansible_distribution}}.yaml'
        - 'install-base-pkgs-{{ansible_os_family}}.yaml'

    - name: Install haveged for low entropy rejecting ssh connections
      block:
        - name: Install haveged package
          package: name=haveged state=latest
        - name: Enable haveged service
          service: name=haveged enabled=yes
      become: yes

    - name: Install LF Recommended Tools
      package:
        name: '{{item}}'
        state: latest
      with_items:
        - ansible
        - crudini
        - facter
        - git
        - git-review
        - graphviz
        - jq
        - sshpass
        - unzip
        - xmlstarlet
        - '{{pkg_gnu_parallel}}'
        - '{{pkg_perl_xml_xpath}}'
        - '{{pkg_xz}}'
      become: yes

    - name: Update /etc/nss-switch.conf to map hostname with IP
      # Update /etc/nss-switch.conf to map hostname with IP instead of using `localhost`
      # from /etc/hosts which is required by some of the Java API's to avoid
      # Java UnknownHostException: "Name or service not known" error.
      shell: sed -i "/^hosts:/s/$/ myhostname/" /etc/nsswitch.conf
      become: yes

    - name: Disable periodic updates
      block:
        - name: Set all periodic update options to 0
          replace:
            path: /etc/apt/apt.conf.d/10periodic
            regexp: '1'
            replace: '0'
        - name: Disable unattended upgrades
          lineinfile:
            path: /etc/apt/apt.conf.d/10periodic
            regexp: '^APT::Periodic::Unattended-Upgrade'
            line: 'APT::Periodic::Unattended-Upgrade "0";'
            create: yes
      when: ansible_distribution == 'Ubuntu'
      become: yes

    - name: System Reseal
      include_tasks: system-reseal.yaml
