---
- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - include_vars: "{{item}}"
      with_first_found:
        - '../playbooks/pkg-names-{{ansible_distribution}}.yaml'
        - '../playbooks/pkg-names-{{ansible_os_family}}.yaml'
        - '../playbooks/pkg-names.yaml'

    - name: Setup SELINUX
      script: ../shell/selinux-setup.sh
      when: ansible_os_family == 'RedHat'
      become: yes

    - name: Allow jenkins user ability to switch Java versions
      copy:
        dest: /etc/sudoers.d/89-jenkins-user-defaults
        content: |
          Defaults:jenkins !requiretty
          jenkins ALL = NOPASSWD: /usr/sbin/alternatives
        validate: /usr/sbin/visudo -cf %s
      when: ansible_os_family == "RedHat"
      become: yes

    - name: Update all packages
      include_tasks: '{{item}}'
      with_first_found:
        - '../playbooks/update-pkgs-{{ansible_distribution}}.yaml'
        - '../playbooks/update-pkgs-{{ansible_os_family}}.yaml'

    - name: Install base packages
      include_tasks: '{{item}}'
      with_first_found:
        - '../playbooks/install-base-pkgs-{{ansible_distribution}}.yaml'
        - '../playbooks/install-base-pkgs-{{ansible_os_family}}.yaml'

    - name: Install haveged for low entropy rejecting ssh connections
      block:
        - name: Install haveged package
          package: name=haveged state=latest
        - name: Enable haveged service
          service: name=haveged enabled=yes
      become: yes

    - name: Install LF Recommended Tools
      package:
        name: '{{item}}'
        state: latest
      with_items:
        - crudini
        - facter
        - git
        - git-review
        - graphviz
        - jq
        - sshpass
        - unzip
        - xmlstarlet
        - '{{pkg_gnu_parallel}}'
        - '{{pkg_perl_xml_xpath}}'
        - '{{pkg_xz}}'
      become: yes

    - name: Install ShellCheck
      vars:
        sc_ver: v0.4.7
      block:
        - name: Fetch ShellCheck
          get_url:
            url: 'https://storage.googleapis.com/shellcheck/shellcheck-{{sc_ver}}.linux.x86_64.tar.xz'
            dest: /tmp/shellcheck.tar.xz
            checksum: sha256:deeea92a4d3a9c5b16ba15210d9c1ab84a2e12e29bf856427700afd896bbdc93
        - name: Unpack ShellCheck
          unarchive:
            src: /tmp/shellcheck.tar.xz
            dest: /tmp
            list_files: yes
            remote_src: yes
        - name: Install ShellCheck to /usr/local/bin/shellcheck
          copy:
            src: '/tmp/shellcheck-{{sc_ver}}/shellcheck'
            dest: /usr/local/bin/shellcheck
            mode: 0755
            owner: root
            remote_src: yes
          become: yes

    - name: Install Hashicorp Packer
      block:
        - name: Fetch Packer
          get_url:
            url: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
            dest: /tmp/packer.zip
            checksum: sha256:b7982986992190ae50ab2feb310cb003a2ec9c5dcba19aa8b1ebb0d120e8686f
        - name: Unpack Packer
          unarchive:
            src: /tmp/packer.zip
            dest: /tmp
            list_files: yes
            remote_src: yes
        - name: Install Packer to /usr/local/bin/packer.io
          copy:
            src: /tmp/packer
            dest: /usr/local/bin/packer
            mode: 0755
            owner: root
            remote_src: yes
          become: yes

    - name: Install Java
      include_tasks: '{{item}}'
      with_first_found:
        - '../playbooks/install-java-{{ansible_distribution}}.yaml'
        - '../playbooks/install-java-{{ansible_os_family}}.yaml'

    - name: Install Python
      package:
        name: '{{item}}'
        state: latest
      with_items:
        - '{{pkg_python2}}'
        - '{{pkg_python2-devel}}'
        - '{{pkg_python2-pip}}'
        - '{{pkg_python2-setuptools}}'
        - '{{pkg_python2-virtualenv}}'
        - '{{pkg_python3}}'
        - '{{pkg_python3-devel}}'
        - '{{pkg_python3-pip}}'
        - '{{pkg_python3-setuptools}}'
        - '{{pkg_python3-virtualenv}}'
      become: yes

    - name: Finalize System
      include_tasks: '{{item}}'
      with_items:
        - '../playbooks/finalize-system-{{ansible_distribution}}.yaml'
        - '../playbooks/finalize-system-{{ansible_os_family}}.yaml'
        - '../playbooks/finalize-system.yaml'

    - name: System Reseal
      include_tasks: ../playbooks/system-reseal.yaml
