---
- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - include_vars: "{{item}}"
      with_first_found:
        - '../playbooks/pkg-names-{{ansible_distribution}}.yaml'
        - '../playbooks/pkg-names-{{ansible_os_family}}.yaml'
        - '../playbooks/pkg-names.yaml'

    - name: Setup SELINUX
      script: ../shell/selinux-setup.sh
      when: ansible_os_family == 'RedHat'
      become: yes

    - name: Allow jenkins user ability to switch Java versions
      copy:
        dest: /etc/sudoers.d/89-jenkins-user-defaults
        content: |
          Defaults:jenkins !requiretty
          jenkins ALL = NOPASSWD: ALL
        validate: /usr/sbin/visudo -cf %s
      become: yes

    - name: Update all packages
      include_tasks: '{{item}}'
      with_first_found:
        - '../playbooks/update-pkgs-{{ansible_distribution}}.yaml'
        - '../playbooks/update-pkgs-{{ansible_os_family}}.yaml'

    - name: Install base packages
      include_tasks: '{{item}}'
      with_first_found:
        - '../playbooks/install-base-pkgs-{{ansible_distribution}}.yaml'
        - '../playbooks/install-base-pkgs-{{ansible_os_family}}.yaml'

    - name: Install haveged for low entropy rejecting ssh connections
      block:
        - name: Install haveged package
          package: name=haveged state=latest
        - name: Enable haveged service
          service: name=haveged enabled=yes
      become: yes

    - name: Install LF Recommended Tools
      package:
        name: '{{item}}'
        state: latest
      with_items:
        - ansible
        - crudini
        - facter
        - git
        - git-review
        - graphviz
        - jq
        - sshpass
        - unzip
        - xmlstarlet
        - '{{pkg_gnu_parallel}}'
        - '{{pkg_perl_xml_xpath}}'
        - '{{pkg_xz}}'
      become: yes

    - name: Install Facter from PuppetLabs
      include_tasks: '{{item}}'
      with_first_found:
        - '../playbooks/install-puppet-agent-{{ansible_distribution}}.yaml'
        - '../playbooks/install-puppet-agent-{{ansible_os_family}}.yaml'

    - name: Install ShellCheck
      vars:
        sc_ver: v0.4.7
      block:
        - name: Fetch ShellCheck
          get_url:
            url: 'https://storage.googleapis.com/shellcheck/shellcheck-{{sc_ver}}.linux.x86_64.tar.xz'
            dest: /tmp/shellcheck.tar.xz
            checksum: sha256:deeea92a4d3a9c5b16ba15210d9c1ab84a2e12e29bf856427700afd896bbdc93
        - name: Unpack ShellCheck
          unarchive:
            src: /tmp/shellcheck.tar.xz
            dest: /tmp
            list_files: yes
            remote_src: yes
        - name: Install ShellCheck to /usr/local/bin/shellcheck
          copy:
            src: '/tmp/shellcheck-{{sc_ver}}/shellcheck'
            dest: /usr/local/bin/shellcheck
            mode: 0755
            owner: root
            remote_src: yes
          become: yes

    - name: Install Java
      include_tasks: '{{item}}'
      with_first_found:
        - '../playbooks/install-java-{{ansible_distribution}}.yaml'
        - '../playbooks/install-java-{{ansible_os_family}}.yaml'

    - name: Install Python
      package:
        name: '{{item}}'
        state: latest
      with_items:
        - '{{pkg_python2}}'
        - '{{pkg_python2_dev}}'
        - '{{pkg_python2_pip}}'
        - '{{pkg_python2_setuptools}}'
        - '{{pkg_python2_virtualenv}}'
        - '{{pkg_python3}}'
        - '{{pkg_python3_dev}}'
        - '{{pkg_python3_pip}}'
        - '{{pkg_python3_setuptools}}'
        - '{{pkg_python3_virtualenv}}'
      become: yes

    - name: Update /etc/nss-switch.conf to map hostname with IP
      # Update /etc/nss-switch.conf to map hostname with IP instead of using `localhost`
      # from /etc/hosts which is required by some of the Java API's to avoid
      # Java UnknownHostException: "Name or service not known" error.
      shell: sed -i "/^hosts:/s/$/ myhostname/" /etc/nsswitch.conf
      become: yes

    - name: Disable periodic updates
      block:
        - name: Set all periodic update options to 0
          replace:
            path: /etc/apt/apt.conf.d/10periodic
            regexp: '1'
            replace: '0'
        - name: Disable unattended upgrades
          lineinfile:
            path: /etc/apt/apt.conf.d/10periodic
            regexp: '^APT::Periodic::Unattended-Upgrade'
            line: 'APT::Periodic::Unattended-Upgrade "0";'
            create: yes
      when: ansible_distribution == 'Ubuntu'
      become: yes

    - name: System Reseal
      include_tasks: ../playbooks/system-reseal.yaml
