---
- name: Baseline for all builds
  hosts: all
  become_user: root
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:
    - name: Fix CentOS EOL repository configuration
      ansible.builtin.script: fix-centos-repos.sh
      become: true
      when:
        - ansible_facts['os_family'] == 'RedHat'
      ignore_errors: false

    - name: Pre-task system update
      ansible.builtin.include_role:
        name: lfit.system-update

    - name: Install base packages
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - "install-base-pkgs-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
        - "install-base-pkgs-{{ ansible_os_family }}.yaml"
        - "install-base-pkgs-{{ ansible_distribution }}.yaml"

    - name: Allow jenkins user sudo access
      ansible.builtin.copy:
        dest: /etc/sudoers.d/89-jenkins-user-defaults
        content: |
          Defaults:jenkins !requiretty
          jenkins ALL=(ALL) NOPASSWD:ALL
        validate: /usr/sbin/visudo -cf %s
        owner: root
        group: root
        mode: "0644"
      become: true

  roles:
    - lfit.lf-recommended-tools
    - lfit.lf-dev-libs
    - lfit.haveged-install
    - lfit.java-install
    - lfit.puppet-install
    - lfit.python-install
    - lfit.shellcheck-install
    - lfit.sysstat-install

  post_tasks:
    - name: Update /etc/nss-switch.conf to map hostname with IP
      # Update /etc/nss-switch.conf to map hostname with IP instead of using `localhost`
      # from /etc/hosts which is required by some of the Java API's to avoid
      # Java UnknownHostException: "Name or service not known" error.
      ansible.builtin.replace:
        path: /etc/nsswitch.conf
        regexp: '^hosts:(\s+.*)?$'
        replace: 'hosts:\1 myhostname'
        backup: true
      become: true

    - name: Disable periodic updates
      when: ansible_distribution == 'Ubuntu'
      become: true
      block:
        - name: Set all periodic update options to 0
          ansible.builtin.replace:
            path: /etc/apt/apt.conf.d/10periodic
            regexp: "1"
            replace: "0"
        - name: Set all auto update options to 0
          ansible.builtin.replace:
            path: /etc/apt/apt.conf.d/20auto-upgrades
            regexp: "1"
            replace: "0"
        - name: Disable unattended upgrades # noqa risky-file-permissions
          ansible.builtin.lineinfile:
            path: /etc/apt/apt.conf.d/10periodic
            regexp: "^APT::Periodic::Unattended-Upgrade"
            line: 'APT::Periodic::Unattended-Upgrade "0";'
            create: true
        - name: Uninstall unattended upgrades
          ansible.builtin.apt:
            name: unattended-upgrades
            state: absent
        - name: Prevent unattended upgrades from being installed
          ansible.builtin.dpkg_selections:
            name: unattended-upgrades
            selection: hold
        - name: Disable apt-daily.* systemd services
          ansible.builtin.systemd:
            name: "{{ service }}"
            enabled: false
            masked: true
          with_items:
            - apt-daily.service
            - apt-daily.timer
            - apt-daily-upgrade.service
            - apt-daily-upgrade.timer
          loop_control:
            loop_var: service

    - name: System Reseal
      ansible.builtin.script: system-reseal.sh
      become: true
