---
- name: Devstack Pre pip CentOS
  import_playbook: ../common-packer/provision/baseline.yaml

- name: Devstack pre-pip for CentOS
  hosts: all
  become_user: root
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:
    - name: Pre-task system update
      ansible.builtin.include_role:
        name: lfit.system-update

  tasks:
    - name: "Install devstack dependencies" # noqa literal-compare
      become: true
      block:
        - name: Install xpath dependencies
          ansible.builtin.yum:
            name:
              - perl-XML-XPath
              - crudini
            state: present
          become: true
        - name: Install non-baseline requirements
          ansible.builtin.yum:
            name:
              - libxml2-devel
              - libxslt-devel
              - libffi-devel
              - openssl-devel
              - "@development"
            state: present
          become: true
        - name: Check if net link setup exists
          ansible.builtin.stat:
            path: /etc/udev/rules.d/80-net-setup-link.rules
          register: rules_file_exists
        - name: Update net link setup # noqa literal-compare
          ansible.builtin.file:
            src: /dev/null
            dest: /etc/udev/rules.d/80-net-setup-link.rules
            state: link
            force: true
          become: true
          when: rules_file_exists.stat.exists == true
        - name: Install RDMA (InfiniBand/iWARP/RoCE) requirements
          ansible.builtin.yum:
            name:
              - libibverbs
              - libmlx5
            state: present
          become: true
    - name: "Pre-Install yum and pip packages"
      block:
        - name: Create /tmp/devstack directory # noqa risky-file-permissions
          ansible.builtin.file:
            path: /tmp/devstack
            state: directory
            mode: "0755"
        - name: Fetch openstack devstack-dev repo
          ansible.builtin.git:
            repo: https://github.com/openstack-dev/devstack.git
            dest: /tmp/devstack
            version: "{{ os_branch }}"
        - name: "Read openstack devstack dependencies" # noqa no-changed-when
          ansible.builtin.shell: "sed -e 's/#.*//' /tmp/devstack/files/rpms/general"
          register: sed_output
          args:
            warn: false
        - name: "Install non-baseline requirements for {{ os_branch }}"
          ansible.builtin.yum: # noqa no-changed-when
            name: "{{ sed_output.stdout_lines }}"
            state: present
          become: true
        - name: Clone openstack core projects
          ansible.builtin.git:
            repo: 'https://github.com/openstack/{{ item }}.git'
            dest: '/tmp/devstack/{{ item }}'
            version: '{{ os_branch }}'
          with_items:
            - requirements
            - keystone
            - glance
            - cinder
            - neutron
            - nova
            - horizon
        - name: Install pip dependencies # noqa no-changed-when
          ansible.builtin.shell: |
            cd "{{ item }}"
            git branch -a
            cd ..
            pwd
            pip install -c requirements/upper-constraints.txt -e "{{ item }}"
            pip install -c requirements/upper-constraints.txt -r "{{ item }}/test-requirements.txt"
            # ignore non-zero return code
            exit 0
          args:
            chdir: /tmp/devstack
            warn: false
          with_items:
            - requirements
            - keystone
            - glance
            - cinder
            - neutron
            - nova
            - horizon
          become: true

    - name: "Install openvswitch from relevant openstack branch"
      block:
        - name: "Install CentOS openstack release {{ rdo_branch }}"
          ansible.builtin.yum:
            name: "centos-release-openstack-{{ rdo_branch }}"
            state: present
          become: true
        - name: "Install openvswitch 2.8.2 for stable/queens"
          ansible.builtin.yum:
            name: openvswitch-2.8.2-1.el7
            state: present
            disable_gpg_check: true
          when: rdo_branch == 'queens'
          become: true
        - name: "Install openvswitch latest for stable/rocky"
          ansible.builtin.yum:
            name: openvswitch
            state: present
            disable_gpg_check: true
          when: rdo_branch == 'rocky'
          become: true

    # Workaround for git deps conflict on rocky
    - name: Swap to git
      become: true
      block:
        - name: Gather rpm package facts
          ansible.builtin.package_facts:
            manager: auto
        - name: Replace git2u with git # noqa no-changed-when command-instead-of-module
          ansible.builtin.command: yum replace -y git2u --replace-with git
          when: ansible_facts.packages['git2u'] is defined

    - name: "Cleanup devstack directory"
      block:
        - name: "Removing /tmp/devstack"
          ansible.builtin.file:
            path: /tmp/devstack
            state: absent
          become: true
