---
- import_playbook: ../common-packer/provision/baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=lfit.system-update

  tasks:
    - name: "Install devstack dependencies"
      block:
        - name: Install xpath dependencies (CentOS/RedHat)
          yum:
            name:
              - perl-XML-XPath
              - crudini
            state: present
          become: true
          when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
        - name: Install xpath dependencies (Ubuntu/Debian)
          apt:
            name:
              - libxml-xpath-perl
              - crudini
            state: present
          become: true
          when: ansible_distribution == "Ubuntu"  or ansible_distribution == "Debian"
        - name: Installing non-baseline requirements (CentOS/RedHat)
          yum:
            name:
              - libxml2-devel
              - libxslt-devel
              - libffi-devel
              - openssl-devel
              - "@development"
            state: present
          become: true
          when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
        - name: Installing non-baseline requirements (Ubuntu/Debian)
          apt:
            name:
              - libxml2-dev
              - libxslt-dev
              - libffi-dev
              - libssl-dev
              - build-essential
            state: present
          become: true
          when: ansible_distribution == "Ubuntu"  or ansible_distribution == "Debian"
        - name: check if net link setup exists
          stat:
            path: /etc/udev/rules.d/80-net-setup-link.rules
          register: rules_file_exists
        - name: Update net link setup
          file:
            src: /dev/null
            dest: /etc/udev/rules.d/80-net-setup-link.rules
            state: link
            force: yes
          become: true
          when: rules_file_exists.stat.exists == true
