---
- name: Import baseline
  import_playbook: ../common-packer/provision/baseline.yaml

- name: Devstack
  hosts: all
  become_user: root
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:
    - name: Pre-task system update
      ansible.builtin.include_role:
        name: lfit.system-update

  tasks:
    - name: "Install devstack dependencies"
      become: true
      block:
        - name: Install xpath dependencies (CentOS/RedHat)
          ansible.builtin.yum:
            name:
              - perl-XML-XPath
              - crudini
            state: present
          become: true
          when: ansible_os_family == 'RedHat'
        - name: Install xpath dependencies (Ubuntu/Debian)
          ansible.builtin.apt:
            name:
              - libxml-xpath-perl
              - crudini
            state: present
          become: true
          when: ansible_os_family == 'Debian'
        - name: Installing non-baseline requirements (CentOS/RedHat)
          ansible.builtin.yum:
            name:
              - libxml2-devel
              - libxslt-devel
              - libffi-devel
              - openssl-devel
              - "@development"
            state: present
          become: true
          when: ansible_os_family == 'RedHat'
        - name: Installing non-baseline requirements (Ubuntu/Debian)
          ansible.builtin.apt:
            name:
              - libxml2-dev
              - libxslt-dev
              - libffi-dev
              - libssl-dev
              - build-essential
            state: present
          become: true
          when: ansible_os_family == 'Debian'
        - name: Check if net link setup exists
          ansible.builtin.stat:
            path: /etc/udev/rules.d/80-net-setup-link.rules
          register: rules_file_exists
        - name: Update net link setup # noqa literal-compare
          ansible.builtin.file:
            src: /dev/null
            dest: /etc/udev/rules.d/80-net-setup-link.rules
            state: link
            force: true
          become: true
          when: rules_file_exists.stat.exists
