---
- import_playbook: baseline.yml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=system-update

  roles:
    - docker-install

  post_tasks:
    - name: System Reseal
      include_tasks: system-reseal.yaml
