---
- name: Import baseline
  import_playbook: baseline.yaml

- name: Docker
  hosts: all
  become_user: root
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:
    - name: Pre-tasks system update
      ansible.builtin.include_role:
        name: lfit.system-update

  roles:
    - { role: lfit.docker-install, mtu: 1458 }

  post_tasks:
    - name: System Reseal
      ansible.builtin.script: system-reseal.sh
      become: true
