---
- import_playbook: baseline.yaml

- hosts: all
  become_user: root
  become_method: sudo

  pre_tasks:
    - include_role: name=lfit.system-update

  roles:
    - role: lfit.docker-install
      mtu:
        - 1458

  post_tasks:
    - name: System Reseal
      script: system-reseal.sh
      become: true
