---

- hosts: all

  tasks:
    - name: Install Tools
      win_chocolatey:
        name: '{{item}}'
        state: present
      with_items:
        - cmake
        - curl
        - git
        - openssh
        - python2
        - python3
        - vim
        - wget
        - zulu8

    - name: Install CMake
      win_chocolatey:
        name: cmake
        state: present
        install_args: ADD_CMAKE_TO_PATH=System

    - name: Install Visual Studio Community Edition
      win_chocolatey:
        name: '{{item}}'
      with_items:
        - visualstudio2017community
        - visualstudio2017-workload-nativedesktop

    - name: Build and Install zlib
      win_shell: |
        $env.Path += ";C:\Program Files\CMake\Bin"
        $env.Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\"
        curl -o c:\zlib.zip https://zlib.net/zlib1211.zip
        unzip -d c:\ c:\zlib.zip
        cd c:\zlib-1.2.11
        cmake -DCMAKE_INSTALL_PREFIX=C:\lib\zlib -G "Visual Studio 15 Win64"
        msbuild INSTALL.vcxproj
        cd c:\
        rm -r c:\zlib-1.2.11 c:\zlib.zip
