---

- hosts: all

  tasks:
    - name: Install Tools
      win_chocolatey:
        name: '{{pkg}}'
        state: present
      with_items:
        - cmake
        - curl
        - git
        - openssh
        - python2
        - python3
        - vim
        - visualstudio2017community
        - wget
        - zulu8
      loop_control:
        loop_var: pkg

    - name: Install CMake
      win_chocolatey:
        name: cmake
        state: present
        install_args: ADD_CMAKE_TO_PATH=System

    - name: Install Visual Studio Community Edition
      win_chocolatey:
        name: '{{pkg}}'
      with_items:
        - visualstudio2017community
        - visualstudio2017-workload-nativedesktop
      loop_control:
        loop_var: pkg
