---

- hosts: all

  tasks:
    - name: Install Tools
      win_chocolatey:
        name: '{{item}}'
        state: present
      with_items:
        - cmake
        - curl
        - git
        - python2
        - python3
        - unzip
        - vim
        - wget
        - zip
        - zulu8

    - name: Install OpenSSH
      win_chocolatey:
        name: openssh
        state: present
        params: /SSHAgentFeature

    - name: Install CMake
      win_chocolatey:
        name: cmake
        state: present
        install_args: ADD_CMAKE_TO_PATH=System

    - name: Install Visual Studio Community Edition
      win_chocolatey:
        name: '{{item}}'
      with_items:
        - visualstudio2017community
        - visualstudio2017-workload-nativedesktop

    - name: Build and Install zlib
      block:
        - name: Copy install-zlib.ps1 script
          win_copy:
            src: windows/install-zlib.ps1
            dest: C:\install-zlib.ps1
        - name: Build and Install zlib
          win_shell: C:\install-zlib.ps1
        - name: Cleanup
          win_file:
            path: C:\install-zlib.ps1
            state: absent
