---
dependency:
  name: galaxy
  options:
    role-file: requirements.yaml
  enabled: true
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: CentOS
    image: centos:7
    groups:
      - centos
  - name: Ubuntu
    image: ubuntu:16.04
provisioner:
  name: ansible
  playbook: playbook.yml
  inventory:
    group_vars:
      centos:
        haveged_service_enable: false
        sysstat_service_enable: false
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
